quarkus.http.port=8620
quarkus.http.host=0.0.0.0
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user_command
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bd_command
#EXTERNALIZAR
#quarkus.datasource.username=${BD_USERNAME}
#quarkus.datasource.password=${BD_PASSWORD}
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bd_command
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# Configurar Hibernate (opcional)
quarkus.hibernate-orm.database.generation=update
# Generar jar
#mvn clean package -DuberJar=true -DskipTests

