quarkus.http.port=8620
quarkus.http.host=0.0.0.0
quarkus.datasource.db-kind=${QUARKUS_DATASOURCE_DB_KIND}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
#EXTERNALIZAR
#quarkus.datasource.username=${BD_USERNAME}
#quarkus.datasource.password=${BD_PASSWORD}
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bd_command
quarkus.datasource.jdbc.driver=${QUARKUS_DATASOURCE_JDBC_DRIVER}

# Configurar Hibernate (opcional)
quarkus.hibernate-orm.database.generation=${QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION}
# Generar jar
#mvn clean package -DuberJar=true -DskipTests
