version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: lafacil
      POSTGRES_USER: miusuario
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  quarkus-app:
    build: .
    container_name: quarkus_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
